language: python
python:
- '3.9'
dist: trusty
sudo: false
addons:
  ssh_known_hosts:
  - 65.21.54.162
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- cp .travis/id_rsa ~/.ssh/deploy_rsa
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
build:
- provider: script
  skip_cleanup: true
  script:
  - pip install -r app/requirements.txt
  - cd app
  - pytest
  on:
    branch: main
deploy:
- provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: main
