language: python
python:
  - "3.9"
os: linux
dist: focal
addons:
  ssh_known_hosts:
  - 65.21.54.162

before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- cp ./deploy_key ~/.ssh/deploy_rsa
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa

install:
  - pip install -r app/requirements.txt

script:
  - cd app
  - pytest
  - bash ../deploy.sh

