version: '3.1'

services:
  app:
    build: ./app
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - mongo
    env_file:
      - .env
    # Create a volume for syncing development action to container
    volumes:
      - ./app:/app

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: gists_pipe
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: gists_pipe
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://gists_pipe:password@mongo:27017/